SPECIAL_FORMS = [
    {
        "form_type": "S-1",
        "filing_name": "Stock Offering",
        "keys": [
            "Prospectus summary",
            "Risk factors",
            "Use of proceeds",
            "Dilution",
            "Selling shareholders",
            "Plan of distribution",
            "Description of securities",
            "Legal proceedings",
            "Business description",
            "Management's discussion and analysis (MD&A)",
            "Financial statements",
            "Management and corporate governance",
            "Executive compensation",
            "Market price of and dividends on common equity",
            "Related party transactions",
            "Selected financial data",
            "Risk factors",
            "Legal opinion",
            "Experts",
            "Incorporation by reference",
        ],
    },
    {
        "form_type": "FWP",
        "filing_name": "Free Writing Prospectus",
        "keys": [
            "Offering Details",
            "Use of Proceeds",
            "Risk Factors",
            "Company Overview",
            "Financial Information",
            "Management Team",
            "Underwriting Details",
            "Legal Matters",
            "Market and Industry Data",
            "Investment Thesis",
            "Offering Structure",
            "Tax Considerations",
            "Industry Comparisons",
            "Capitalization Structure",
            "Recent Developments",
            "Regulatory Compliance",
            "Distribution Channels",
            "Offering Timeline",
            "Investor Considerations",
            "Forward-Looking Statements",
        ],
    },
    {
        "form_type": "424B2",
        "filing_name": "Prospectus",
        "keys": [
            "Issuer Name",
            "Date of Filing",
            "Securities Being Offered",
            "Offering Price and Terms",
            "Use of Proceeds",
            "Risk Factors",
            "Legal Counsel Information",
            "Underwriting Details",
            "Offering Timeline and Closing Date",
            "Regulatory Authority Addressed",
            "Compliance with Filing Requirements",
            "Market Impact of Filing",
            "Shareholder Communication Plan",
            "Regulatory Review Process",
            "Market Surveillance Measures",
            "Prospectus Delivery Procedures",
            "Financial Statements Included",
            "Contact Information for Further Inquiries",
            "Applicable Regulations",
            "Explanation to Investors",
        ],
    },
    {
        "form_type": "SC 13G",
        "filing_name": "Large Transaction Reports",
        "keys": [
            "Filer Identification",
            "Issuer Name and Ticker Symbol",
            "Date of Filing",
            "Filer Category (e.g., Institutional Investor)",
            "Beneficial Ownership Reporting Thresholds",
            "Number of Shares Beneficially Owned",
            "Percentage of Class Owned",
            "Filing Person's Relationship with Issuer",
            "Purpose of Filing",
            "Control Person Status",
            "Schedule 13G Filing Deadline",
            "Legal Counsel Information",
            "Regulatory Authority Addressed",
            "Compliance with Reporting Requirements",
            "Market Impact of Filing",
            "Disclosure Obligations",
            "Shareholder Communication Plan",
            "Regulatory Authority Response (if received)",
            "Market Surveillance Measures",
            "Contact Information for Further Inquiries",
        ],
    },
    {
        "form_type": "DEF 14A",
        "filing_name": "Proxy Statement",
        "keys": [
            "Director Nominees and Elections",
            "Executive Compensation",
            "Corporate Governance Policies",
            "Shareholder Proposals",
            "Voting Procedures",
            "Related Party Transactions",
            "Board Committees",
            "Board Independence",
            "Equity Compensation Plans",
            "Say-on-Pay Vote",
            "CEO Pay Ratio",
            "Performance Graph",
            "Legal Proceedings Involving Directors",
            "Beneficial Ownership of Securities",
            "Security Ownership of Certain Beneficial Owners",
            "Section 16(a) Beneficial Ownership Reporting Compliance",
            "Corporate Social Responsibility Initiatives",
            "Shareholder Engagement Efforts",
            "Proxy Solicitation Costs",
        ],
    },
    {
        "form_type": "PX14A6G",
        "filing_name": "Activist Shareholder Proposal",
        "keys": [
            "Issuer Name",
            "Date of Filing",
            "Meeting Date",
            "Agenda Items",
            "Shareholder Proposals",
            "Board of Directors Composition",
            "Executive Compensation Details",
            "Proxy Voting Information",
            "Shareholder Voting Procedures",
            "Legal Counsel Information",
            "Regulatory Authority Addressed",
            "Compliance with Filing Requirements",
            "Market Impact of Filing",
            "Disclosure Obligations",
            "Shareholder Communication Plan",
            "Regulatory Review Process",
            "Market Surveillance Measures",
            "Proxy Solicitation Expenses",
            "Contact Information for Further Inquiries",
            "Applicable Regulations",
        ],
    },
]
